AWSTemplateFormatVersion: '2010-09-09'
Description: ECS Cluster and Service using Fargate and ECR Image

Parameters:
  BaseECRImageName:
    Type: String
    Default: ecr-9-12 # replace with ECR Repository Name
  VPCId:
    Type: String
    Default: vpc-0e050bd47d6aa5448
  Subnet1:
    Type: String
    Default: subnet-0ba2f71e6f21019d1
  Subnet2:
    Type: String
    Default: subnet-08c457dfacd8ab001
  SecurityGroup:
    Type: String
    Default: sg-060c5c2866a559b0f
  CognitoUserPoolName:
    Type: String
    Description: The name of the User Pool
    Default: "JRS-Register-Dev"
  UserPoolClientName:
    Type: String
    Description: The name of the User Pool Client
    Default: "JRS-Register-Dev"

Resources:
  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties: 
      ClusterName: TestNodeCluster-v8

  ECSTaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: ecsTaskExecutionRolePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - ecr:GetDownloadUrlForLayer
                  - ecr:BatchGetImage
                  - ecr:BatchCheckLayerAvailability
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                  - ecr:*
                  - cognito-idp:*
                Resource: '*'

  # Add CloudWatch Log Group to ensure it exists before the ECS task runs
  CloudWatchLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /ecs/test-node-service-autoscaling-v8
      RetentionInDays: 7  # Set retention based on your needs

  ECSTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: test-node-task
      Cpu: '512'  # Update based on your requirement
      Memory: '1024'  # Update based on your requirement
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      ExecutionRoleArn: !GetAtt ECSTaskExecutionRole.Arn
      ContainerDefinitions:
        - Name: test-node-container-v8
          Image: !Sub "${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${BaseECRImageName}:latest"
          Essential: true
          PortMappings:
            - ContainerPort: 3000
          Memory: 512
          Cpu: 256
          Environment:   # Add environment variables if needed
            - Name: NODE_ENV
              Value: production
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: /ecs/test-node-service-autoscaling-v8
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: ecs

  ECSService:
    Type: AWS::ECS::Service
    DependsOn:
      - ECSCluster
      - ECSLoadBalancer
      - ECSLoadBalancerListener
      - CloudWatchLogGroup  # Ensure log group is created before service starts
    Properties:
      ServiceName: test-node-service-v8
      Cluster: !Ref ECSCluster
      TaskDefinition: !Ref ECSTaskDefinition
      DesiredCount: 2  # Number of containers to run
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          Subnets:
            - !Ref Subnet1
            - !Ref Subnet2
          SecurityGroups:
            - !Ref SecurityGroup
      LoadBalancers:
        - ContainerName: test-node-container-v8
          ContainerPort: 3000
          TargetGroupArn: !Ref ECSLoadBalancerTargetGroup

  ECSLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: test-node-load-balancer-v8
      Scheme: internet-facing
      Subnets:
        - !Ref Subnet1
        - !Ref Subnet2
      SecurityGroups:
        - !Ref SecurityGroup
      Type: application

  ECSLoadBalancerListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref ECSLoadBalancerTargetGroup
      LoadBalancerArn: !Ref ECSLoadBalancer
      Port: 80
      Protocol: HTTP

  ECSLoadBalancerTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: test-node-target-group-v8
      Port: 3000
      Protocol: HTTP
      VpcId: !Ref VPCId
      HealthCheckProtocol: HTTP
      HealthCheckPath: /
      TargetType: ip

##########################################
# Auto Scaling Resources for ECS Service #
##########################################

  ECSServiceScalingTarget:
    Type: AWS::ApplicationAutoScaling::ScalableTarget
    DependsOn:
      - ECSService  # Ensure the service is created first
    Properties: 
      MaxCapacity: 4  # Maximum number of containers to scale to
      MinCapacity: 1  # Minimum number of containers
      ResourceId: !Sub "service/TestNodeCluster-v8/test-node-service-v8"  # This is set manually as the ARN causes issues
      RoleARN: !GetAtt ECSTaskExecutionRole.Arn
      ScalableDimension: ecs:service:DesiredCount
      ServiceNamespace: ecs

  ECSServiceScalingPolicy:
    Type: AWS::ApplicationAutoScaling::ScalingPolicy
    DependsOn:
      - ECSServiceScalingTarget  # Ensure the scaling target exists before the policy
    Properties:
      PolicyName: ECSAutoScalingPolicy
      PolicyType: TargetTrackingScaling
      ResourceId: !Sub "service/TestNodeCluster-v8/test-node-service-v8"  # Ensure correct resource format
      ScalableDimension: ecs:service:DesiredCount  # Correct scalable dimension to match ECSServiceScalingTarget
      ServiceNamespace: ecs  # Correct namespace for ECS
      TargetTrackingScalingPolicyConfiguration:
        PredefinedMetricSpecification:
          PredefinedMetricType: ECSServiceAverageCPUUtilization
        TargetValue: 50.0
        ScaleInCooldown: 60
        ScaleOutCooldown: 60

##########################################
# EventBridge Rule and Lambda Function   #
##########################################

  ECRUpdateRule:
    Type: AWS::Events::Rule
    Properties:
      Name: ECRUpdateRule-v8
      EventPattern:
        source:
          - "aws.ecr"
        detail-type:
          - "ECR Image Action"
        detail:
          actionType:
            - "PUSH"
          result:
            - "SUCCESS"
      Targets:
        - Arn: !GetAtt ECSUpdateLambdaFunction.Arn
          Id: "ECRUpdateLambdaTarget"

  ECSUpdateLambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: LambdaECSUpdatePolicy # Adds AmazonECS_FullAccess equivalent policy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
            - Sid: ECSIntegrationsManagementPolicy
              Effect: Allow
              Action:
                - application-autoscaling:DeleteScalingPolicy
                - application-autoscaling:DeregisterScalableTarget
                - application-autoscaling:DescribeScalableTargets
                - application-autoscaling:DescribeScalingActivities
                - application-autoscaling:DescribeScalingPolicies
                - application-autoscaling:PutScalingPolicy
                - application-autoscaling:RegisterScalableTarget
                - appmesh:DescribeVirtualGateway
                - appmesh:DescribeVirtualNode
                - appmesh:ListMeshes
                - appmesh:ListVirtualGateways
                - appmesh:ListVirtualNodes
                - autoscaling:CreateAutoScalingGroup
                - autoscaling:CreateLaunchConfiguration
                - autoscaling:DeleteAutoScalingGroup
                - autoscaling:DeleteLaunchConfiguration
                - autoscaling:Describe*
                - autoscaling:UpdateAutoScalingGroup
                - cloudformation:CreateStack
                - cloudformation:DeleteStack
                - cloudformation:DescribeStack*
                - cloudformation:UpdateStack
                - cloudwatch:DeleteAlarms
                - cloudwatch:DescribeAlarms
                - cloudwatch:GetMetricStatistics
                - cloudwatch:PutMetricAlarm
                - codedeploy:BatchGetApplicationRevisions
                - codedeploy:BatchGetApplications
                - codedeploy:BatchGetDeploymentGroups
                - codedeploy:BatchGetDeployments
                - codedeploy:ContinueDeployment
                - codedeploy:CreateApplication
                - codedeploy:CreateDeployment
                - codedeploy:CreateDeploymentGroup
                - codedeploy:GetApplication
                - codedeploy:GetApplicationRevision
                - codedeploy:GetDeployment
                - codedeploy:GetDeploymentConfig
                - codedeploy:GetDeploymentGroup
                - codedeploy:GetDeploymentTarget
                - codedeploy:ListApplicationRevisions
                - codedeploy:ListApplications
                - codedeploy:ListDeploymentConfigs
                - codedeploy:ListDeploymentGroups
                - codedeploy:ListDeployments
                - codedeploy:ListDeploymentTargets
                - codedeploy:RegisterApplicationRevision
                - codedeploy:StopDeployment
                - ec2:AssociateRouteTable
                - ec2:AttachInternetGateway
                - ec2:AuthorizeSecurityGroupIngress
                - ec2:CancelSpotFleetRequests
                - ec2:CreateInternetGateway
                - ec2:CreateLaunchTemplate
                - ec2:CreateRoute
                - ec2:CreateRouteTable
                - ec2:CreateSecurityGroup
                - ec2:CreateSubnet
                - ec2:CreateVpc
                - ec2:DeleteLaunchTemplate
                - ec2:DeleteSubnet
                - ec2:DeleteVpc
                - ec2:Describe*
                - ec2:DetachInternetGateway
                - ec2:DisassociateRouteTable
                - ec2:ModifySubnetAttribute
                - ec2:ModifyVpcAttribute
                - ec2:RequestSpotFleet
                - ec2:RunInstances
                - ecs:*
                - elasticfilesystem:DescribeAccessPoints
                - elasticfilesystem:DescribeFileSystems
                - elasticloadbalancing:CreateListener
                - elasticloadbalancing:CreateLoadBalancer
                - elasticloadbalancing:CreateRule
                - elasticloadbalancing:CreateTargetGroup
                - elasticloadbalancing:DeleteListener
                - elasticloadbalancing:DeleteLoadBalancer
                - elasticloadbalancing:DeleteRule
                - elasticloadbalancing:DeleteTargetGroup
                - elasticloadbalancing:DescribeListeners
                - elasticloadbalancing:DescribeLoadBalancers
                - elasticloadbalancing:DescribeRules
                - elasticloadbalancing:DescribeTargetGroups
                - events:DeleteRule
                - events:DescribeRule
                - events:ListRuleNamesByTarget
                - events:ListTargetsByRule
                - events:PutRule
                - events:PutTargets
                - events:RemoveTargets
                - fsx:DescribeFileSystems
                - iam:ListAttachedRolePolicies
                - iam:ListInstanceProfiles
                - iam:ListRoles
                - lambda:ListFunctions
                - logs:CreateLogGroup
                - logs:DescribeLogGroups
                - logs:FilterLogEvents
                - route53:CreateHostedZone
                - route53:DeleteHostedZone
                - route53:GetHealthCheck
                - route53:GetHostedZone
                - route53:ListHostedZonesByName
                - servicediscovery:CreatePrivateDnsNamespace
                - servicediscovery:CreateService
                - servicediscovery:DeleteService
                - servicediscovery:GetNamespace
                - servicediscovery:GetOperation
                - servicediscovery:GetService
                - servicediscovery:ListNamespaces
                - servicediscovery:ListServices
                - servicediscovery:UpdateService
                - sns:ListTopics
              Resource: '*'

            - Sid: SSMPolicy
              Effect: Allow
              Action:
                - ssm:GetParameter
                - ssm:GetParameters
                - ssm:GetParametersByPath
              Resource: "arn:aws:ssm:*:*:parameter/aws/service/ecs*"

            - Sid: ManagedCloudformationResourcesCleanupPolicy
              Effect: Allow
              Action:
                - ec2:DeleteInternetGateway
                - ec2:DeleteRoute
                - ec2:DeleteRouteTable
                - ec2:DeleteSecurityGroup
              Resource: "*"
              Condition:
                StringLike:
                  ec2:ResourceTag/aws:cloudformation:stack-name: "EC2ContainerService-*"

            - Sid: TasksPassRolePolicy
              Effect: Allow
              Action: iam:PassRole
              Resource: "*"
              Condition:
                StringLike:
                  iam:PassedToService: "ecs-tasks.amazonaws.com"

            - Sid: InfrastructurePassRolePolicy
              Effect: Allow
              Action: iam:PassRole
              Resource: "arn:aws:iam::*:role/ecsInfrastructureRole"
              Condition:
                StringEquals:
                  iam:PassedToService: "ecs.amazonaws.com"

            - Sid: InstancePassRolePolicy
              Effect: Allow
              Action: iam:PassRole
              Resource: "arn:aws:iam::*:role/ecsInstanceRole*"
              Condition:
                StringLike:
                  iam:PassedToService:
                    - "ec2.amazonaws.com"
                    - "ec2.amazonaws.com.cn"

            - Sid: AutoScalingPassRolePolicy
              Effect: Allow
              Action: iam:PassRole
              Resource: "arn:aws:iam::*:role/ecsAutoscaleRole*"
              Condition:
                StringLike:
                  iam:PassedToService:
                    - "application-autoscaling.amazonaws.com"
                    - "application-autoscaling.amazonaws.com.cn"

            - Sid: ServiceLinkedRoleCreationPolicy
              Effect: Allow
              Action: iam:CreateServiceLinkedRole
              Resource: "*"
              Condition:
                StringLike:
                  iam:AWSServiceName:
                    - "ecs.amazonaws.com"
                    - "autoscaling.amazonaws.com"
                    - "ecs.application-autoscaling.amazonaws.com"
                    - "spot.amazonaws.com"
                    - "spotfleet.amazonaws.com"

            - Sid: ELBTaggingPolicy
              Effect: Allow
              Action: elasticloadbalancing:AddTags
              Resource: "*"
              Condition:
                StringEquals:
                  elasticloadbalancing:CreateAction:
                    - "CreateTargetGroup"
                    - "CreateRule"
                    - "CreateListener"
                    - "CreateLoadBalancer"
  
  ECSUpdateLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Handler: index.handler
      Role: !GetAtt ECSUpdateLambdaExecutionRole.Arn
      Runtime: python3.9
      Code:
        ZipFile: |
          import json
          import boto3
          
          ecs_client = boto3.client('ecs')

          def handler(event, context):
              cluster_name = "TestNodeCluster-v8"
              service_name = "test-node-service-autoscaling-v8"
              
              response = ecs_client.describe_task_definition(
                  taskDefinition=service_name
              )
              
             # Register a new task definition with the updated image
              container_definitions = response['taskDefinition']['containerDefinitions']
              for container in container_definitions:
                  if container['name'] == 'test-node-container':
                      container['image'] = f"{event['account']}.dkr.ecr.{event['region']}.amazonaws.com/{event['detail']['repositoryName']}:latest"
              
              new_task_def = ecs_client.register_task_definition(
                  family=response['taskDefinition']['family'],
                  containerDefinitions=container_definitions,
                  cpu=response['taskDefinition']['cpu'],
                  memory=response['taskDefinition']['memory'],
                  networkMode=response['taskDefinition']['networkMode'],
                  requiresCompatibilities=response['taskDefinition']['requiresCompatibilities']
              )

              # Update the ECS service to use the new task definition
              ecs_client.update_service(
                  cluster=cluster_name,
                  service=service_name,
                  taskDefinition=new_task_def['taskDefinition']['taskDefinitionArn']
              )
      Timeout: 30

  ##########################################
  # Cognito Resources                      #
  ##########################################

  UserPool:
    Type: "AWS::Cognito::UserPool"
    Properties:
      AccountRecoverySetting:
        RecoveryMechanisms:
          - Name: verified_email
            Priority: 1
      AdminCreateUserConfig:
        AllowAdminCreateUserOnly: true
      UserPoolName: !Ref CognitoUserPoolName
      MfaConfiguration: "OFF"
      Schema:
        - Name: email
          AttributeDataType: String
          Mutable: false
          Required: true
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireLowercase: True
          RequireNumbers: True
          RequireSymbols: false
          RequireUppercase: True
      UsernameAttributes:
        - email
      UsernameConfiguration:
        CaseSensitive: False

  UserPoolClient:
    Type: "AWS::Cognito::UserPoolClient"
    Properties:
      ClientName: !Ref UserPoolClientName
      GenerateSecret: false
      ExplicitAuthFlows:
        - ALLOW_CUSTOM_AUTH
        - ALLOW_USER_PASSWORD_AUTH
        - ALLOW_USER_SRP_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
      PreventUserExistenceErrors: ENABLED
      UserPoolId: !Ref UserPool

Outputs:
  ECSServiceName:
    Description: Name of the ECS Service
    Value: !Ref ECSService
  LoadBalancerDNS:
    Description: DNS Name of the Load Balancer
    Value: !GetAtt ECSLoadBalancer.DNSName
